import type { ProjectileSpec, WeaponKind } from './types';

export const TRACTOR_FUEL_COST_PER_FRAME = 0.08;

export const PROJECTILES: Record<Exclude<WeaponKind, 'tractor'>, ProjectileSpec> = {
  small: {
    count: 1,
    damage: 1,
    fireIntervalMs: 500,
    fuelCost: 0,
    impact: 0.2,
    lifetimeMs: 1000,
    radius: 2,
    recoil: 0.5,
    speed: 20,
    speedVariance: 0,
    spread: 0,
  },
  pusher: {
    count: 1,
    damage: 0.2,
    fireIntervalMs: 60,
    fuelCost: 0.2,
    impact: 0.8,
    lifetimeMs: 1500,
    radius: 4,
    recoil: 0.05,
    speed: 10,
    speedVariance: 0,
    spread: 0,
  },
  shotgun: {
    count: 8,
    damage: 3,
    fireIntervalMs: 600,
    fuelCost: 3,
    impact: 0.02,
    lifetimeMs: 350,
    radius: 3,
    recoil: 3,
    speed: 12,
    speedVariance: 0.3,
    spread: Math.PI / 3,
  },
  blackHole: {
    count: 1,
    damage: 0,
    fireIntervalMs: 2000,
    fuelCost: 12,
    impact: 0,
    lifetimeMs: 10000,
    radius: 6,
    recoil: 4,
    speed: 1,
    speedVariance: 0,
    spread: 0,
  },
  inspectionProbe: {
    count: 1,
    damage: 0,
    fireIntervalMs: 600,
    fuelCost: 0,
    impact: 0,
    lifetimeMs: 10000,
    radius: 5,
    recoil: 0,
    speed: 18,
    speedVariance: 0,
    spread: 0,
  },
};
