import { PLAYER_TURRET_MUZZLE_OFFSET } from '../player/textures';
import type {
  DischargedWeaponKind,
  WeaponFireSpec,
} from './types';

const FUEL_GUN_BLOB_SPAWN_OFFSET = PLAYER_TURRET_MUZZLE_OFFSET + 28;

export const WEAPON_FIRE_CONFIGS: Record<DischargedWeaponKind, WeaponFireSpec> = {
  small: {
    emissions: [
      {
        count: 1,
        degraded: { lifetimeScale: 0.5, speedScale: 0.5 },
        entity: {
          absorbedFuel: 0,
          ageMs: 0,
          airResistance: 0,
          collapseStartedAt: null,
          damage: 1,
          impact: 0.2,
          kind: 'small',
          lifetimeMs: 1000,
          radius: 2,
        },
        inheritShooterVelocity: true,
        spawnOffset: PLAYER_TURRET_MUZZLE_OFFSET,
        speed: 20,
        speedVariance: 0,
        spread: 0,
        type: 'projectile',
      },
    ],
    fireIntervalMs: 500,
    fuelCost: 0,
    recoil: 0.5,
  },
  pusher: {
    emissions: [
      {
        count: 1,
        entity: {
          absorbedFuel: 0,
          ageMs: 0,
          airResistance: 0,
          collapseStartedAt: null,
          damage: 0.2,
          impact: 0.8,
          kind: 'pusher',
          lifetimeMs: 1500,
          radius: 4,
        },
        inheritShooterVelocity: true,
        spawnOffset: PLAYER_TURRET_MUZZLE_OFFSET,
        speed: 10,
        speedVariance: 0,
        spread: 0,
        type: 'projectile',
      },
    ],
    fireIntervalMs: 60,
    fuelCost: 0.2,
    recoil: 0.05,
  },
  shotgun: {
    emissions: [
      {
        count: 8,
        entity: {
          absorbedFuel: 0,
          ageMs: 0,
          airResistance: 0.02,
          collapseStartedAt: null,
          damage: 3,
          impact: 0.02,
          kind: 'shotgun',
          lifetimeMs: 350,
          radius: 3,
        },
        inheritShooterVelocity: true,
        lifetimeVariance: { maxScale: 1, minScale: 0.7 },
        spawnOffset: PLAYER_TURRET_MUZZLE_OFFSET,
        speed: 12,
        speedVariance: 0.3,
        spread: Math.PI / 3,
        type: 'projectile',
        volleys: 2,
      },
    ],
    fireIntervalMs: 600,
    fuelCost: 3,
    recoil: 3,
  },
  blackHole: {
    emissions: [
      {
        count: 1,
        entity: {
          absorbedFuel: 0,
          ageMs: 0,
          airResistance: 0.01,
          blackHoleMass: 1,
          collapseStartedAt: null,
          damage: 0,
          impact: 0,
          kind: 'blackHole',
          lifetimeMs: 10000,
          radius: 6,
        },
        inheritShooterVelocity: true,
        spawnOffset: PLAYER_TURRET_MUZZLE_OFFSET,
        speed: 1,
        speedVariance: 0,
        spread: 0,
        type: 'projectile',
      },
    ],
    fireIntervalMs: 2000,
    fuelCost: 12,
    recoil: 4,
  },
  fuelGun: {
    emissions: [
      {
        count: 1,
        entity: {
          affectedByPlanetGravity: false,
          airResistance: 0.015,
          collectableDelayMs: 550,
        },
        inheritShooterVelocity: true,
        spawnOffset: FUEL_GUN_BLOB_SPAWN_OFFSET,
        speed: 6,
        spread: 0,
        type: 'fuelBlob',
      },
    ],
    fireIntervalMs: 60,
    fuelCost: 5,
    recoil: 0,
  },
  inspectionProbe: {
    emissions: [
      {
        count: 1,
        entity: {
          absorbedFuel: 0,
          ageMs: 0,
          airResistance: 0.01,
          collapseStartedAt: null,
          damage: 0,
          impact: 0,
          kind: 'inspectionProbe',
          lifetimeMs: 10000,
          radius: 5,
        },
        inheritShooterVelocity: true,
        spawnOffset: PLAYER_TURRET_MUZZLE_OFFSET,
        speed: 18,
        speedVariance: 0,
        spread: 0,
        type: 'projectile',
      },
    ],
    fireIntervalMs: 600,
    fuelCost: 0,
    recoil: 0,
  },
};
