import type { ProjectileSpec, WeaponKind } from './types';

export const PROJECTILES: Record<Exclude<WeaponKind, 'tractor'>, ProjectileSpec> = {
  small: {
    count: 1,
    damage: 2,
    fireIntervalMs: 200,
    fuelCost: 0.75,
    impact: 0.2,
    lifetimeMs: 500,
    radius: 4,
    recoil: 0.3,
    speed: 15,
    spread: 0,
  },
  pusher: {
    count: 1,
    damage: 0.2,
    fireIntervalMs: 40,
    fuelCost: 0.2,
    impact: 0.5,
    lifetimeMs: 1000,
    radius: 6,
    recoil: 0.1333,
    speed: 8,
    spread: 0,
  },
  shotgun: {
    count: 12,
    damage: 1,
    fireIntervalMs: 600,
    fuelCost: 3,
    impact: 0.02,
    lifetimeMs: 250,
    radius: 3,
    recoil: 0.9,
    speed: 12,
    spread: Math.PI / 4,
  },
  blackHole: {
    count: 1,
    damage: 0,
    fireIntervalMs: 2000,
    fuelCost: 12,
    impact: 0,
    lifetimeMs: 10000,
    radius: 6,
    recoil: 4,
    speed: 1,
    spread: 0,
  },
  inspectionProbe: {
    count: 1,
    damage: 0,
    fireIntervalMs: 600,
    fuelCost: 0,
    impact: 0,
    lifetimeMs: 10000,
    radius: 5,
    recoil: 0,
    speed: 18,
    spread: 0,
  },
};
