export const RIFT_PORTAL_RADIUS_X = 172;
export const RIFT_PORTAL_RADIUS_Y = 92;
export const RIFT_PORTAL_APERTURE_RADIUS_X = RIFT_PORTAL_RADIUS_X;
export const RIFT_PORTAL_APERTURE_RADIUS_Y = RIFT_PORTAL_RADIUS_Y;
export const RIFT_OPEN_DURATION_MS = 420;
export const RIFT_CLOSE_DURATION_MS = 520;

export const ARCADE_RIFT_INITIAL_INTERVAL_MS = 2600;
export const ARCADE_RIFT_MIN_INTERVAL_MS = 30150;
export const ARCADE_RIFT_INTERVAL_DECAY_PER_BURST_MS = 70;
export const ARCADE_RIFT_BASE_ASTEROIDS = 4;
export const ARCADE_RIFT_ASTEROIDS_PER_BURST = 0.55;
export const ARCADE_RIFT_MAX_ASTEROIDS = 18;
